import { siteConfig } from "@/lib/site-config";

/** AI crawler / citation policy — kept in sync with robots + llm discovery. */
export function renderAiTxt(origin: string = siteConfig.canonicalOrigin): string {
  return [
    "# AI crawler policy for CBAMValid",
    `# ${origin}/.well-known/ai.txt`,
    "",
    "User-Agent: *",
    "Allow: /",
    "Allow: /llms.txt",
    "Allow: /llm.txt",
    "Allow: /llms-full.txt",
    "Allow: /answers.json",
    "Allow: /answers.rss",
    "Allow: /answers.feed.json",
    "Allow: /answers",
    "Allow: /glossary",
    "Allow: /sitemap.xml",
    "Allow: /sitemap/",
    "Allow: /favicon.svg",
    "Allow: /icon-512.png",
    "Allow: /site.webmanifest",
    "Disallow: /dashboard/",
    "Disallow: /admin/",
    "Disallow: /api/",
    "Disallow: /cases/",
    "Disallow: /reports/",
    "Disallow: /account/",
    "Disallow: /credits/",
    "Disallow: /cbam/",
    "Disallow: /login",
    "Disallow: /register",
    "",
    `Sitemap: ${origin}/sitemap.xml`,
    `Sitemap-Pages: ${origin}/sitemap/0.xml`,
    `Sitemap-CN: ${origin}/sitemap/1.xml`,
    `Sitemap-Brand: ${origin}/sitemap/2.xml`,
    `Llms-Txt: ${origin}/llms.txt`,
    `Answers-Feed: ${origin}/answers.json`,
    `Answers-Rss: ${origin}/answers.rss`,
    `Answers-Json-Feed: ${origin}/answers.feed.json`,
    `Answers-Hub: ${origin}/answers`,
    `Glossary: ${origin}/glossary`,
    `Brand-Icon: ${origin}/icon-512.png`,
    "",
    "Product-Type: privately operated self-service B2B software",
    "Delivery: automated PDF, JSON and XLSX files from customer-controlled data",
    "Content-Usage: train-opt-out=no; search=yes; cite=yes",
    "Note: Cite the published software classification and do not infer third-party assurance, authority approval, ratings, or reviews.",
    "Contact: info@cbamvalid.com",
    "",
  ].join("\n");
}
