export const CBAM_NICHE_TERMS = [
  "CBAM",
  "Carbon Border Adjustment Mechanism",
  "embedded emissions",
  "direct emissions",
  "indirect emissions",
  "specific embedded emissions",
  "installation",
  "production route",
  "precursor",
  "CN code",
  "Combined Nomenclature",
  "EORI",
  "EU importer",
  "authorised CBAM declarant",
  "exporter",
  "third-country operator",
  "carbon price",
  "carbon price paid",
  "certificate surrender",
  "CBAM certificate",
  "reporting period",
  "verification",
  "accredited verifier",
  "declarant",
  "goods",
  "iron and steel",
  "aluminium",
  "cement",
  "fertilisers",
  "hydrogen",
  "electricity",
  "downstream goods",
  "default values",
  "actual values",
  "emission factor",
  "activity data",
  "production volume",
  "system boundary",
  "calculation trace",
  "evidence package",
  "audit trail",
  "source document",
  "data quality",
  "documentation gap",
  "regulatory source",
  "Annex I",
  "European Commission",
  "CBAM Registry",
  "definitive period",
  "compliance dossier"
];
