import type { SeoRouteContract } from "./types";
import { listIndexablePublicCnEntries } from "./cn-public-registry";

const LASTMOD_IA = "2026-07-27";

const STATIC_ROUTES: readonly SeoRouteContract[] = [
  {
    path: "/",
    pageType: "homepage",
    indexability: "index",
    title: "CBAMValid — CBAM Evidence Validation and Report Preparation",
    description:
      "When EU buyers ask for actual CBAM emissions evidence, prepare one installation and one reporting year in a sealed verifier-preparation pack. Draft free. Pay USD 249 once to lock that working file. Same-file corrections included. Not an accredited verification opinion.",
    h1: "CBAM Exporter Final Evidence Report",
    canonicalPath: "/",
    primaryIntent: "CBAM verification preparation software",
    audience: ["non-EU producers", "exporters", "EU importers", "CBAM reporting teams"],
    sitemapEligible: true,
    schemaTypes: ["Organization", "WebSite", "WebPage", "WebApplication", "FAQPage"],
    internalLinkTargets: [
      "/product",
      "/pricing",
      "/methodology",
      "/answers",
      "/glossary",
      "/cn-code",
      "/cbam-2026-definitive-period",
      "/cbam-verification-preparation",
      "/cbam-non-eu-producer-guide",
      "/about",
      "/contact",
      "/privacy",
      "/terms",
      "/legal-notice",
    ],
    regulatorySourceIds: ["REG_2023_956", "REG_2025_2083"],
    factualLastModified: LASTMOD_IA,
  },
  {
    path: "/product",
    pageType: "product",
    indexability: "index",
    title: "When Spreadsheets Fail Under Verifier Questions | CBAMValid Product",
    description:
      "See the CBAMValid Exporter Verification Preparation Pack: deterministic calculations, evidence register, QC gates, and sealed verifier-ready deliverables — prepared for independent review.",
    h1: "When spreadsheets fail under verifier questions",
    canonicalPath: "/product",
    primaryIntent: "CBAM verification preparation product",
    audience: ["exporters", "operators", "importers"],
    sitemapEligible: true,
    schemaTypes: ["Product", "Offer", "WebPage", "BreadcrumbList"],
    internalLinkTargets: ["/", "/pricing", "/sample-dossier", "/how-it-works"],
    regulatorySourceIds: ["REG_2023_956", "IMPL_2025_2546"],
    factualLastModified: LASTMOD_IA,
  },
  {
    path: "/pricing",
    pageType: "pricing",
    indexability: "index",
    title: "Pricing | USD 249 Pay-at-Lock Preparation Pack",
    description:
      "USD 249 one-time: pay when you lock one working file (one operator, one installation, one year). Draft free. Same-file corrections included. New file = new payment. No subscription.",
    h1: "Exporter Verification Preparation Pack",
    canonicalPath: "/pricing",
    primaryIntent: "CBAMValid pricing",
    audience: ["exporters", "procurement", "compliance managers"],
    sitemapEligible: true,
    schemaTypes: ["Product", "Offer", "WebPage", "BreadcrumbList", "FAQPage"],
    internalLinkTargets: ["/", "/product", "/sample-dossier", "/terms", "/refund-policy"],
    regulatorySourceIds: [],
    factualLastModified: LASTMOD_IA,
  },
  {
    path: "/how-it-works",
    pageType: "product",
    indexability: "index",
    title: "From Raw Plant Data to a Sealed Package | How CBAMValid Works",
    description:
      "One factory + one year = one working file. Link evidence, clear blockers, pay once to lock, then correct and re-lock the same file as needed. New file = new payment.",
    h1: "From raw plant data to a sealed package — without email chaos",
    canonicalPath: "/how-it-works",
    primaryIntent: "CBAMValid workflow",
    audience: ["exporters", "data preparers"],
    sitemapEligible: true,
    schemaTypes: ["WebPage", "BreadcrumbList"],
    internalLinkTargets: ["/", "/product", "/pricing", "/sample-dossier", "/terms"],
    regulatorySourceIds: ["REG_2023_956"],
    factualLastModified: LASTMOD_IA,
  },
  {
    path: "/sample-dossier",
    pageType: "product",
    indexability: "index",
    title: "Sample CBAM Verification Preparation Dossier | CBAMValid",
    description:
      "Browse a 16-page interactive sample CBAMValid preparation dossier: page thumbs, document stage, and contents panel with integrity-manifest expectations before you buy.",
    h1: "See the dossier before you purchase",
    canonicalPath: "/sample-dossier",
    primaryIntent: "CBAM sample dossier",
    audience: ["exporters", "importers", "verifiers (read-only preview)"],
    sitemapEligible: true,
    schemaTypes: ["WebPage", "BreadcrumbList"],
    internalLinkTargets: ["/", "/product", "/pricing", "/verify"],
    regulatorySourceIds: ["REG_2023_956", "IMPL_2025_2546", "IMPL_2025_2547", "DEL_2025_2551"],
    factualLastModified: LASTMOD_IA,
  },
  {
    path: "/methodology",
    pageType: "methodology",
    indexability: "index",
    title: "When a Verifier Asks Which Rules — Dated CBAM Methodology",
    description:
      "Authoritative CBAMValid calculations pin to a named, versioned ruleset in the sealed dossier. Historical seals keep the ruleset they were built against.",
    h1: "When a verifier asks “which rules?”, you need a dated answer",
    canonicalPath: "/methodology",
    primaryIntent: "CBAM calculation methodology",
    audience: ["exporters", "technical preparers", "reviewers"],
    sitemapEligible: true,
    schemaTypes: ["WebPage", "BreadcrumbList"],
    internalLinkTargets: ["/", "/cn-code", "/cbam-embedded-emissions-calculation", "/cbam-actual-vs-default-values"],
    regulatorySourceIds: ["REG_2023_956", "IMPL_2025_2547", "IMPL_2025_2546"],
    factualLastModified: LASTMOD_IA,
  },
  {
    path: "/cn-code",
    pageType: "cn-hub",
    indexability: "index",
    title: "CBAM CN-Code Scope Verification Hub | Validate Product",
    description:
      "Verify whether goods fall within CBAM Combined Nomenclature scope and open sector-specific CN decision pages.",
    h1: "Verify CBAM CN-Code Scope",
    canonicalPath: "/cn-code",
    primaryIntent: "CBAM CN code scope",
    audience: ["exporters", "importers", "customs teams"],
    sitemapEligible: true,
    schemaTypes: ["CollectionPage", "ItemList", "BreadcrumbList", "FAQPage"],
    internalLinkTargets: [
      "/",
      "/methodology",
      "/cbam-cn-code-scope",
      ...listIndexablePublicCnEntries().map((entry) => `/cn-code/${entry.cnCode}`),
    ],
    regulatorySourceIds: ["REG_2023_956"],
    factualLastModified: LASTMOD_IA,
  },
  {
    path: "/verify",
    pageType: "verification",
    indexability: "index",
    title: "Verify a CBAMValid Dossier Signature | Public Integrity Check",
    description:
      "Learn how CBAMValid public signature verification works for sealed dossier integrity. Individual tokens are not mass-indexed.",
    h1: "Verify a Dossier",
    canonicalPath: "/verify",
    primaryIntent: "CBAMValid dossier verification",
    audience: ["importers", "verifiers", "buyers"],
    sitemapEligible: true,
    schemaTypes: ["WebPage", "BreadcrumbList"],
    internalLinkTargets: ["/", "/sample-dossier", "/product"],
    regulatorySourceIds: [],
    factualLastModified: LASTMOD_IA,
  },
  {
    path: "/about",
    pageType: "about",
    indexability: "index",
    title: "About CBAMValid | Independent CBAM Preparation — Clear Limits",
    description:
      "CBAMValid is an independent CBAM preparation platform with published independence boundaries and academic mathematical review — not an official EU or accredited verifier service.",
    h1: "Independent CBAM preparation — with clear limits",
    canonicalPath: "/about",
    primaryIntent: "About CBAMValid",
    audience: ["prospective customers"],
    sitemapEligible: true,
    schemaTypes: ["AboutPage", "BreadcrumbList", "FAQPage", "Organization"],
    internalLinkTargets: ["/", "/contact", "/methodology", "/legal-notice", "/privacy", "/product"],
    regulatorySourceIds: [],
    factualLastModified: LASTMOD_IA,
  },
  {
    path: "/contact",
    pageType: "contact",
    indexability: "index",
    title: "Contact CBAMValid | Support Before a Buyer Deadline",
    description:
      "Email info@cbamvalid.com for technical, dossier, and billing help. Legal and privacy contacts are published for GDPR and data-subject requests.",
    h1: "Need help before a buyer deadline?",
    canonicalPath: "/contact",
    primaryIntent: "Contact CBAMValid",
    audience: ["customers", "prospects"],
    sitemapEligible: true,
    schemaTypes: ["ContactPage", "BreadcrumbList", "FAQPage"],
    internalLinkTargets: ["/", "/privacy", "/terms", "/refund-policy", "/cookie-policy", "/legal-notice", "/about", "/pricing"],
    regulatorySourceIds: [],
    factualLastModified: LASTMOD_IA,
  },
  {
    path: "/answers",
    pageType: "guide",
    indexability: "index",
    title: "CBAMValid Answer Bank | Direct Answers with Evidence Boundaries",
    description:
      "Quotable CBAMValid answers for pay-at-lock pricing, payment timing, independence, sealing, and verification preparation — each with evidence links. Not an accredited verification opinion.",
    h1: "CBAMValid answer bank",
    canonicalPath: "/answers",
    primaryIntent: "CBAMValid FAQ and answer engine hub",
    audience: ["exporters", "importers", "answer engines", "procurement"],
    sitemapEligible: true,
    schemaTypes: ["CollectionPage", "FAQPage", "BreadcrumbList", "ItemList"],
    internalLinkTargets: ["/", "/glossary", "/pricing", "/product", "/methodology", "/how-it-works"],
    regulatorySourceIds: ["REG_2023_956", "REG_2025_2083"],
    factualLastModified: LASTMOD_IA,
  },
  {
    path: "/glossary",
    pageType: "guide",
    indexability: "index",
    title: "CBAM Glossary | Embedded Emissions, CN Codes, Verifiers | CBAMValid",
    description:
      "Operational definitions for CBAM entities used across CBAMValid authority chains: embedded emissions, CN codes, actual vs default values, precursors, and preparation-pack terms.",
    h1: "CBAM terms used across CBAMValid",
    canonicalPath: "/glossary",
    primaryIntent: "CBAM entity glossary for exporters",
    audience: ["exporters", "operators", "answer engines"],
    sitemapEligible: true,
    schemaTypes: ["CollectionPage", "DefinedTermSet", "BreadcrumbList"],
    internalLinkTargets: ["/", "/answers", "/methodology", "/cn-code", "/cbam-embedded-emissions-calculation"],
    regulatorySourceIds: ["REG_2023_956", "IMPL_2025_2546"],
    factualLastModified: LASTMOD_IA,
  },
  {
    path: "/privacy",
    pageType: "legal",
    indexability: "index",
    title: "Privacy Notice | CBAMValid Data Handling and Security Rules",
    description:
      "Read the CBAMValid Privacy Notice explaining data collection, security measures, and compliance policies.",
    h1: "Privacy Notice",
    canonicalPath: "/privacy",
    primaryIntent: "Privacy notice",
    audience: ["platform users"],
    sitemapEligible: true,
    schemaTypes: ["WebPage", "BreadcrumbList"],
    internalLinkTargets: ["/", "/contact"],
    regulatorySourceIds: [],
    factualLastModified: LASTMOD_IA,
  },
  {
    path: "/terms",
    pageType: "legal",
    indexability: "index",
    title: "Terms of Service | CBAMValid Platform and Usage Agreements",
    description:
      "Terms for CBAMValid: pay-at-lock commercial unit, same-file corrections, new-file payment rule, delivery, disclaimers, and Paddle checkout.",
    h1: "Terms of Service",
    canonicalPath: "/terms",
    primaryIntent: "Terms of service",
    audience: ["platform users"],
    sitemapEligible: true,
    schemaTypes: ["WebPage", "BreadcrumbList"],
    internalLinkTargets: ["/", "/contact", "/privacy", "/pricing", "/refund-policy"],
    regulatorySourceIds: [],
    factualLastModified: LASTMOD_IA,
  },
  {
    path: "/refund-policy",
    pageType: "legal",
    indexability: "index",
    title: "Refund Policy | CBAMValid Evidence Package Purchase Terms",
    description:
      "Refund rules for CBAMValid pay-at-lock purchases: unused unlocks within 14 days, failed delivery, duplicate charges, and Paddle processing.",
    h1: "Refund Policy",
    canonicalPath: "/refund-policy",
    primaryIntent: "Refund policy",
    audience: ["customers"],
    sitemapEligible: true,
    schemaTypes: ["WebPage", "BreadcrumbList"],
    internalLinkTargets: ["/", "/contact", "/terms", "/pricing"],
    regulatorySourceIds: [],
    factualLastModified: LASTMOD_IA,
  },
  {
    path: "/cookie-policy",
    pageType: "legal",
    indexability: "index",
    title: "Cookie Policy | CBAMValid Tracking Technologies Notice",
    description: "Read how CBAMValid uses essential cookies and tracking technologies.",
    h1: "Cookie Policy",
    canonicalPath: "/cookie-policy",
    primaryIntent: "Cookie policy",
    audience: ["site visitors"],
    sitemapEligible: true,
    schemaTypes: ["WebPage", "BreadcrumbList"],
    internalLinkTargets: ["/", "/privacy"],
    regulatorySourceIds: [],
    factualLastModified: LASTMOD_IA,
  },
  {
    path: "/legal-notice",
    pageType: "legal",
    indexability: "index",
    title: "Legal Notice | CBAMValid Corporate Identity Information",
    description: "View the legal notice and corporate identity information for CBAMValid.",
    h1: "Legal Notice",
    canonicalPath: "/legal-notice",
    primaryIntent: "Legal notice",
    audience: ["site visitors"],
    sitemapEligible: true,
    schemaTypes: ["WebPage", "BreadcrumbList"],
    internalLinkTargets: ["/", "/contact"],
    regulatorySourceIds: [],
    factualLastModified: LASTMOD_IA,
  },
  {
    path: "/cbam-2026-definitive-period",
    pageType: "guide",
    indexability: "index",
    title: "CBAM 2026 Definitive Period | Declaration Timetable",
    description:
      "What changed in the CBAM definitive period from 2026, including the 30 September 2027 declaration and certificate surrender deadline for 2026 imports.",
    h1: "CBAM 2026 Definitive Period",
    canonicalPath: "/cbam-2026-definitive-period",
    primaryIntent: "CBAM definitive period 2026",
    audience: ["importers", "non-EU producers", "compliance teams"],
    sitemapEligible: true,
    schemaTypes: ["WebPage", "BreadcrumbList"],
    internalLinkTargets: [
      "/",
      "/methodology",
      "/cbam-verification-preparation",
      "/pricing",
      "/cbam-certificate-price",
      "/cbam-embedded-emissions-calculation",
      "/cbam-exporter-evidence-requirements",
      "/cbam-methodology",
    ],
    regulatorySourceIds: ["REG_2023_956", "REG_2025_2083", "IMPL_2025_2546"],
    factualLastModified: LASTMOD_IA,
  },
  {
    path: "/cbam-embedded-emissions-calculation",
    pageType: "guide",
    indexability: "index",
    title: "How to Calculate CBAM Embedded Emissions | Direct and Indirect",
    description:
      "Decision guide to CBAM embedded emissions: direct emissions, electricity-related indirect emissions, precursors, and evidence requirements.",
    h1: "Calculate CBAM Embedded Emissions",
    canonicalPath: "/cbam-embedded-emissions-calculation",
    primaryIntent: "how to calculate embedded emissions",
    audience: ["exporters", "technical preparers"],
    sitemapEligible: true,
    schemaTypes: ["WebPage", "BreadcrumbList"],
    internalLinkTargets: ["/methodology", "/cbam-actual-vs-default-values", "/product"],
    regulatorySourceIds: ["REG_2023_956", "IMPL_2025_2547"],
    factualLastModified: LASTMOD_IA,
  },
  {
    path: "/cbam-actual-vs-default-values",
    pageType: "guide",
    indexability: "index",
    title: "CBAM Actual Values vs Default Values | Decision Guide",
    description:
      "When to use actual embedded emissions versus default values, verification implications, and what CBAMValid prepares.",
    h1: "Actual Values vs Default Values",
    canonicalPath: "/cbam-actual-vs-default-values",
    primaryIntent: "CBAM actual vs default values",
    audience: ["exporters", "importers"],
    sitemapEligible: true,
    schemaTypes: ["WebPage", "BreadcrumbList"],
    internalLinkTargets: ["/cbam-default-values", "/methodology", "/cbam-verification-preparation"],
    regulatorySourceIds: ["REG_2023_956", "REG_2025_2083", "IMPL_2025_2547"],
    factualLastModified: LASTMOD_IA,
  },
  {
    path: "/cbam-default-values",
    pageType: "guide",
    indexability: "index",
    title: "CBAM Default Values | Multi-Dimensional Official Factors",
    description:
      "Why CBAM default values are not a single number per CN code, and how country, route, year and emission dimension matter.",
    h1: "CBAM Default Values",
    canonicalPath: "/cbam-default-values",
    primaryIntent: "CBAM default values",
    audience: ["exporters", "importers", "consultants"],
    sitemapEligible: true,
    schemaTypes: ["WebPage", "BreadcrumbList"],
    internalLinkTargets: ["/cbam-actual-vs-default-values", "/methodology", "/cn-code"],
    regulatorySourceIds: ["REG_2023_956", "IMPL_2025_2547"],
    factualLastModified: LASTMOD_IA,
  },
  {
    path: "/cbam-certificate-price",
    pageType: "guide",
    indexability: "index",
    title: "CBAM Certificate Price | 2026 Quarterly Cadence Explained",
    description:
      "How CBAM certificate prices are published and used. Quarterly price calculation in 2026 is not the same as transitional quarterly reporting.",
    h1: "CBAM Certificate Price",
    canonicalPath: "/cbam-certificate-price",
    primaryIntent: "CBAM certificate price",
    audience: ["importers", "finance teams"],
    sitemapEligible: true,
    schemaTypes: ["WebPage", "BreadcrumbList"],
    internalLinkTargets: ["/cbam-2026-definitive-period", "/pricing", "/methodology"],
    regulatorySourceIds: ["IMPL_2025_2548", "REG_2025_2083"],
    factualLastModified: LASTMOD_IA,
  },
  {
    path: "/cbam-verification-preparation",
    pageType: "guide",
    indexability: "index",
    title: "CBAM Verification Preparation Checklist | Operator Evidence Pack",
    description:
      "What operators must prepare before independent accredited verification, and how CBAMValid structures the evidence package.",
    h1: "CBAM Verification Preparation",
    canonicalPath: "/cbam-verification-preparation",
    primaryIntent: "CBAM verifier preparation",
    audience: ["exporters", "operators", "importers"],
    sitemapEligible: true,
    schemaTypes: ["WebPage", "BreadcrumbList"],
    internalLinkTargets: ["/product", "/sample-dossier", "/cbam-exporter-evidence-requirements"],
    regulatorySourceIds: ["IMPL_2025_2546", "REG_2023_956"],
    factualLastModified: LASTMOD_IA,
  },
  {
    path: "/cbam-exporter-evidence-requirements",
    pageType: "guide",
    indexability: "index",
    title: "CBAM Exporter Evidence Requirements | Traceable Data Package",
    description:
      "Evidence lineage requirements for CBAM preparation: hashes, support status, linked fields, and fail-closed sealing gates.",
    h1: "Exporter Evidence Requirements",
    canonicalPath: "/cbam-exporter-evidence-requirements",
    primaryIntent: "CBAM exporter evidence requirements",
    audience: ["exporters", "data preparers"],
    sitemapEligible: true,
    schemaTypes: ["WebPage", "BreadcrumbList"],
    internalLinkTargets: ["/cbam-verification-preparation", "/product", "/methodology"],
    regulatorySourceIds: ["REG_2023_956", "IMPL_2025_2546"],
    factualLastModified: LASTMOD_IA,
  },
  {
    path: "/cbam-non-eu-producer-guide",
    pageType: "guide",
    indexability: "index",
    title: "CBAM Guide for Non-EU Producers | Evidence for EU Buyers",
    description:
      "What non-EU producers need to prepare so EU importers can meet CBAM definitive-period obligations.",
    h1: "CBAM Guide for Non-EU Producers",
    canonicalPath: "/cbam-non-eu-producer-guide",
    primaryIntent: "CBAM non-EU producer guide",
    audience: ["non-EU producers", "exporters"],
    sitemapEligible: true,
    schemaTypes: ["WebPage", "BreadcrumbList"],
    internalLinkTargets: ["/cbam-2026-definitive-period", "/cn-code", "/product"],
    regulatorySourceIds: ["REG_2023_956", "REG_2025_2083"],
    factualLastModified: LASTMOD_IA,
  },
  {
    path: "/cbam-cn-code-scope",
    pageType: "guide",
    indexability: "index",
    title: "CBAM CN Code Scope | Annex I Goods Decision Guide",
    description:
      "How Combined Nomenclature codes determine CBAM goods scope across iron and steel, aluminium, cement, fertilisers, hydrogen and electricity.",
    h1: "CBAM CN Code Scope",
    canonicalPath: "/cbam-cn-code-scope",
    primaryIntent: "CBAM CN code list / scope",
    audience: ["exporters", "importers", "customs"],
    sitemapEligible: true,
    schemaTypes: ["WebPage", "BreadcrumbList"],
    internalLinkTargets: ["/cn-code", "/methodology", "/product"],
    regulatorySourceIds: ["REG_2023_956"],
    factualLastModified: LASTMOD_IA,
  },
  {
    path: "/cbam-methodology",
    pageType: "guide",
    indexability: "index",
    title: "CBAM Methodology Overview | Rulesets and Calculation Trace",
    description:
      "Overview of CBAM methodology choices, ruleset versioning, and why sealed calculation traces must be reproducible.",
    h1: "CBAM Methodology Overview",
    canonicalPath: "/cbam-methodology",
    primaryIntent: "CBAM methodology",
    audience: ["technical preparers", "reviewers"],
    sitemapEligible: true,
    schemaTypes: ["WebPage", "BreadcrumbList"],
    internalLinkTargets: ["/methodology", "/cbam-embedded-emissions-calculation", "/product"],
    regulatorySourceIds: ["REG_2023_956", "IMPL_2025_2547"],
    factualLastModified: LASTMOD_IA,
  },
];

function buildCnDetailRoute(cnCode: string, description: string, sector: string, lastmod: string): SeoRouteContract {
  const short = description.length > 80 ? `${description.slice(0, 77)}...` : description;
  return {
    path: `/cn-code/${cnCode}`,
    pageType: "cn-detail",
    indexability: "index",
    title: `CN ${cnCode}: ${short} | EU CBAM Scope`,
    description: `CBAM scope decision page for CN ${cnCode} (${sector}). Official description, producer data and evidence considerations for verification preparation.`,
    h1: `CN ${cnCode} — CBAM Scope`,
    canonicalPath: `/cn-code/${cnCode}`,
    primaryIntent: `CBAM CN code ${cnCode}`,
    audience: ["exporters", "importers", "customs teams"],
    sitemapEligible: true,
    schemaTypes: ["WebPage", "BreadcrumbList"],
    internalLinkTargets: ["/cn-code", "/cbam-cn-code-scope", "/product", "/methodology"],
    regulatorySourceIds: ["REG_2023_956"],
    factualLastModified: lastmod,
  };
}

const CN_DETAIL_ROUTES: readonly SeoRouteContract[] = listIndexablePublicCnEntries().map((entry) =>
  buildCnDetailRoute(entry.cnCode, entry.description, entry.sector, entry.factualLastModified),
);

export const SEO_ROUTE_REGISTRY: readonly SeoRouteContract[] = [...STATIC_ROUTES, ...CN_DETAIL_ROUTES];

const BY_PATH = new Map(SEO_ROUTE_REGISTRY.map((route) => [route.path, route]));

export function getSeoRoute(path: string): SeoRouteContract | undefined {
  return BY_PATH.get(path);
}

export function requireSeoRoute(path: string): SeoRouteContract {
  const route = getSeoRoute(path);
  if (!route) {
    throw new Error(`SEO registry missing route: ${path}`);
  }
  return route;
}

export function listIndexableSeoRoutes(): readonly SeoRouteContract[] {
  return SEO_ROUTE_REGISTRY.filter((route) => route.indexability === "index");
}

export function listSitemapRoutes(): readonly SeoRouteContract[] {
  return SEO_ROUTE_REGISTRY.filter(
    (route) => route.indexability === "index" && route.sitemapEligible,
  );
}

/** @deprecated Legacy export name — prefer SEO_ROUTE_REGISTRY / getSeoRoute. */
export const seoRegistry: Record<string, SeoRouteContract> = Object.fromEntries(
  SEO_ROUTE_REGISTRY.map((route) => [route.path, route]),
);
