import { SeoMeta } from "./types";

export const seoRegistry: Record<string, SeoMeta> = {
  "/": {
    path: "/",
    pageType: "homepage",
    indexable: true,
    primaryKeyword: "CBAM evidence dossier",
    secondaryKeywords: ["embedded emissions calculation", "CBAM validation"],
    domainNoun: "CBAM evidence preparation",
    pain: "Identifying documentation gaps and missing specific embedded emissions",
    outcome: "Generate auditable CBAM evidence dossier for the EU importer",
    audience: "EU importers and third-country operators",
    title: "CBAMValid — CBAM Evidence Validation and Report Preparation",
    description: "Prepare structured exporter evidence, identify documentation gaps, calculate embedded emissions, and generate an auditable CBAM evidence dossier.",
    h1: "Prepare Auditable CBAM Evidence Dossiers",
    canonicalPath: "/",
    lastModifiedSource: "registry",
    authorityReferences: [],
    schemaTypes: ["Organization", "WebSite", "WebApplication"],
    internalLinkTargets: ["/about", "/methodology", "/cn-code"],
    datePublished: "2024-01-01T00:00:00Z",
    dateModified: new Date().toISOString(),
    qualityContract: {
      userProblem: "EU importers need auditable CBAM evidence dossiers but lack structured tooling",
      decisionEnabled: "Whether to use the platform or manual spreadsheets for CBAM compliance",
      uniqueValueTypes: ["calculator", "expertExperience", "methodology"],
      evidenceRefs: ["EU 2023/956", "EU 2023/1773"],
      limitations: ["Does not replace accredited verifier", "Requires user-provided installation data"],
      lastHumanReviewAt: "2026-07-19",
    },
  },
  "/about": {
    path: "/about",
    pageType: "about",
    indexable: true,
    primaryKeyword: "About CBAMValid",
    secondaryKeywords: ["CBAM software service"],
    domainNoun: "Organization",
    pain: "Need an independent tool to calculate embedded emissions",
    outcome: "Understand CBAMValid mission to compile the CBAM evidence package",
    audience: "EU importers",
    title: "About CBAMValid | Independent CBAM Preparation Service",
    description: "Learn about CBAMValid, an independent software service assisting with CBAM evidence validation and embedded emissions reporting. Understand our team.",
    h1: "About CBAMValid",
    canonicalPath: "/about",
    lastModifiedSource: "registry",
    authorityReferences: [],
    schemaTypes: ["BreadcrumbList"],
    internalLinkTargets: ["/", "/contact", "/methodology"],
  },
  "/methodology": {
    path: "/methodology",
    pageType: "methodology",
    indexable: true,
    primaryKeyword: "CBAM calculation methodology",
    secondaryKeywords: ["embedded emissions formula", "actual values", "default values"],
    domainNoun: "Calculation methodology",
    pain: "Uncertainty regarding EU CBAM specific embedded emissions rules",
    outcome: "Understand our deterministic CBAM calculation trace for the reporting period",
    audience: "Exporters compiling evidence",
    title: "CBAM Calculation Methodology & Regulatory Sources Index",
    description: "Understand the deterministic CBAM calculation methodology we use to calculate direct and indirect embedded emissions under the EU regulation.",
    h1: "Understand CBAM Calculation Methodology",
    canonicalPath: "/methodology",
    lastModifiedSource: "registry",
    authorityReferences: [],
    schemaTypes: ["Article", "BreadcrumbList"],
    internalLinkTargets: ["/", "/cn-code"],
    qualityContract: {
      userProblem: "Exporters must understand which CBAM methodology applies to their installation type",
      decisionEnabled: "Whether to use actual data or EU default values for emission factor calculation",
      uniqueValueTypes: ["methodology", "expertExperience", "dataset"],
      evidenceRefs: ["EU 2023/956 Art.7", "EU 2023/1773 Annex III", "ISO 14064-1"],
      limitations: ["General methodology only", "Installation-specific rules may vary by member state"],
      lastHumanReviewAt: "2026-07-19",
    },
  },
  "/contact": {
    path: "/contact",
    pageType: "contact",
    indexable: true,
    primaryKeyword: "Contact CBAMValid",
    secondaryKeywords: ["CBAMValid support"],
    domainNoun: "Support",
    pain: "Need help using the platform to report specific embedded emissions",
    outcome: "Resolve inquiries quickly to finalize the compliance dossier",
    audience: "Platform users",
    title: "Contact CBAMValid | Dedicated CBAM Compliance Support",
    description: "Contact CBAMValid support for assistance with your CBAM evidence package, billing, calculation inquiries, and finalizing your specific embedded emissions data.",
    h1: "Contact CBAMValid",
    canonicalPath: "/contact",
    lastModifiedSource: "registry",
    authorityReferences: [],
    schemaTypes: ["BreadcrumbList"],
    internalLinkTargets: ["/", "/privacy"],
  },
  "/privacy": {
    path: "/privacy",
    pageType: "legal",
    indexable: true,
    primaryKeyword: "Privacy Notice",
    secondaryKeywords: ["Data handling"],
    domainNoun: "Privacy rules",
    pain: "Data security concerns when handling specific embedded emissions",
    outcome: "Understand data handling for your CBAM compliance dossier",
    audience: "Platform users",
    title: "Privacy Notice | CBAMValid Data Handling and Security Rules",
    description: "Read the CBAMValid Privacy Notice explaining our data collection, security measures, and compliance policies for your CBAM evidence package.",
    h1: "Privacy Notice",
    canonicalPath: "/privacy",
    lastModifiedSource: "registry",
    authorityReferences: [],
    schemaTypes: ["BreadcrumbList"],
    internalLinkTargets: ["/", "/contact"],
  },
  "/terms": {
    path: "/terms",
    pageType: "legal",
    indexable: true,
    primaryKeyword: "Terms of Service",
    secondaryKeywords: ["Usage rules"],
    domainNoun: "Terms",
    pain: "Legal obligations when submitting CBAM specific embedded emissions",
    outcome: "Understand terms for finalizing your CBAM compliance dossier",
    audience: "Platform users",
    title: "Terms of Service | CBAMValid Platform and Usage Agreements",
    description: "Read the Terms of Service governing the use of the CBAMValid platform and digital generation of your CBAM evidence package and calculation trace.",
    h1: "Terms of Service",
    canonicalPath: "/terms",
    lastModifiedSource: "registry",
    authorityReferences: [],
    schemaTypes: ["BreadcrumbList"],
    internalLinkTargets: ["/", "/contact", "/privacy"],
  },
  "/refund-policy": {
    path: "/refund-policy",
    pageType: "legal",
    indexable: true,
    primaryKeyword: "Refund Policy",
    secondaryKeywords: ["Credits refund"],
    domainNoun: "Refunds",
    pain: "Payment disputes for CBAM specific embedded emissions reports",
    outcome: "Understand refund rights for your CBAM evidence package",
    audience: "Customers",
    title: "Refund Policy | CBAMValid Evidence Package Purchase Terms",
    description: "Review the CBAMValid refund policy regarding digital payments and generated CBAM evidence package downloads and specific embedded emissions reporting.",
    h1: "Refund Policy",
    canonicalPath: "/refund-policy",
    lastModifiedSource: "registry",
    authorityReferences: [],
    schemaTypes: ["BreadcrumbList"],
    internalLinkTargets: ["/", "/contact", "/terms"],
  },
  "/cookie-policy": {
    path: "/cookie-policy",
    pageType: "legal",
    indexable: true,
    primaryKeyword: "Cookie Policy",
    secondaryKeywords: ["Tracking technologies"],
    domainNoun: "Cookies",
    pain: "Tracking concerns while reporting specific embedded emissions",
    outcome: "Understand cookie usage during CBAM evidence package preparation",
    audience: "Site visitors",
    title: "Cookie Policy | CBAMValid Tracking Technologies Notice",
    description: "Read our Cookie Policy to learn how CBAMValid uses essential cookies and tracking to secure the application during your CBAM evidence package compilation.",
    h1: "Cookie Policy",
    canonicalPath: "/cookie-policy",
    lastModifiedSource: "registry",
    authorityReferences: [],
    schemaTypes: ["BreadcrumbList"],
    internalLinkTargets: ["/", "/privacy"],
  },
  "/legal-notice": {
    path: "/legal-notice",
    pageType: "legal",
    indexable: true,
    primaryKeyword: "Legal Notice",
    secondaryKeywords: ["Company information"],
    domainNoun: "Legal Notice",
    pain: "Identity verification of the CBAM evidence package provider",
    outcome: "Verify company identity before submitting specific embedded emissions",
    audience: "Site visitors",
    title: "Legal Notice | CBAMValid Corporate Identity Information",
    description: "View the legal notice and corporate identity information for CBAMValid, the independent platform for compiling your EU CBAM evidence package.",
    h1: "Legal Notice",
    canonicalPath: "/legal-notice",
    lastModifiedSource: "registry",
    authorityReferences: [],
    schemaTypes: ["BreadcrumbList"],
    internalLinkTargets: ["/", "/contact"],
  },
  "/cn-code": {
    path: "/cn-code",
    pageType: "cn-code",
    indexable: true,
    primaryKeyword: "CBAM CN-Code Scope",
    secondaryKeywords: ["CN code verification", "Combined Nomenclature"],
    domainNoun: "CN-Code Scope",
    pain: "Checking if a product is in scope for CBAM specific embedded emissions",
    outcome: "Verify CBAM CN-Code Scope for your compliance dossier",
    audience: "Exporters and Importers",
    title: "CBAM CN-Code Scope Verification Hub | Validate Product",
    description: "Verify your CBAM CN-Code Scope to determine if your imported goods fall within the specific embedded emissions regulation and require reporting.",
    h1: "Verify CBAM CN-Code Scope",
    canonicalPath: "/cn-code",
    lastModifiedSource: "registry",
    authorityReferences: [],
    schemaTypes: ["BreadcrumbList", "ItemList"],
    internalLinkTargets: ["/", "/methodology"],
  },
  "/how-it-works": {
    path: "/how-it-works",
    pageType: "guide",
    indexable: true,
    primaryKeyword: "CBAM dossier workflow",
    secondaryKeywords: ["CBAM process steps"],
    domainNoun: "Dossier workflow",
    pain: "Need to clear the documentation gap in specific embedded emissions",
    outcome: "Verify CBAM Registry requirements using a structured compliance dossier",
    audience: "EU importers and operators",
    title: "Understand the CBAM Dossier Workflow Guide | CBAMValid",
    description: "Understand the CBAM dossier workflow. Read how CBAMValid guides you through data entry, evidence validation, quality controls, and report sealing.",
    h1: "Understand the CBAM Dossier Workflow",
    canonicalPath: "/how-it-works",
    lastModifiedSource: "registry",
    authorityReferences: [],
    schemaTypes: ["BreadcrumbList", "HowTo"],
    internalLinkTargets: ["/", "/pricing", "/product"]
  },
  "/pricing": {
    path: "/pricing",
    pageType: "product",
    indexable: true,
    primaryKeyword: "Verification Pack pricing",
    secondaryKeywords: ["credits cost"],
    domainNoun: "Pricing plans",
    pain: "Concerned about costs when calculating direct emissions and indirect emissions",
    outcome: "Purchase credits to unlock your sealed compliance dossier and evidence package",
    audience: "Operators",
    title: "Review CBAM Exporter Verification Pack Pricing | CBAMValid",
    description: "Review CBAM Exporter Verification Pack pricing. Check plans to seal your compliance dossier, calculate embedded emissions, and prepare verification.",
    h1: "Review CBAM Exporter Verification Pack Pricing",
    canonicalPath: "/pricing",
    lastModifiedSource: "registry",
    authorityReferences: [],
    schemaTypes: ["BreadcrumbList", "Product"],
    internalLinkTargets: ["/", "/sample-dossier", "/product"]
  },
  "/product": {
    path: "/product",
    pageType: "product",
    indexable: true,
    primaryKeyword: "CBAM dossier software",
    secondaryKeywords: ["emissions software"],
    domainNoun: "Software application",
    pain: "Struggling to collect and link activity data to specific embedded emissions",
    outcome: "Compile an audit trail and evidence package for the accredited verifier",
    audience: "Operators and importers",
    title: "Verify Compliance with CBAM Dossier Software | CBAMValid",
    description: "Verify compliance using CBAM dossier software. Link raw activity data, track direct emissions, audit your trace, and prepare for accredited verifier.",
    h1: "Verify Compliance with CBAM Dossier Software",
    canonicalPath: "/product",
    lastModifiedSource: "registry",
    authorityReferences: [],
    schemaTypes: ["BreadcrumbList", "WebApplication"],
    internalLinkTargets: ["/", "/how-it-works", "/pricing"],
    qualityContract: {
      userProblem: "Operators need a structured tool to compile CBAM evidence dossiers with proper audit trail",
      decisionEnabled: "Whether CBAMValid software meets verifier requirements vs. manual compilation",
      uniqueValueTypes: ["calculator", "methodology", "firstPartyData"],
      evidenceRefs: ["EU 2023/956", "EU 2023/1773", "GHG Protocol"],
      limitations: ["Does not provide accredited verification", "User responsible for data accuracy"],
      lastHumanReviewAt: "2026-07-19",
    },
  },
  "/sample-dossier": {
    path: "/sample-dossier",
    pageType: "guide",
    indexable: true,
    primaryKeyword: "sample CBAM compliance dossier",
    secondaryKeywords: ["demo report"],
    domainNoun: "Sample dossier",
    pain: "Unsure how to present actual values and system boundary details to the verifier",
    outcome: "Inspect the final compliance dossier layout and calculation trace structure",
    audience: "Importers and verifiers",
    title: "Review a Sample CBAM Compliance Dossier before Sealing",
    description: "Review a sample CBAM compliance dossier. See how the platform structure calculates actual values, links source documents, and shows calculation trace.",
    h1: "Review a Sample CBAM Compliance Dossier",
    canonicalPath: "/sample-dossier",
    lastModifiedSource: "registry",
    authorityReferences: [],
    schemaTypes: ["BreadcrumbList"],
    internalLinkTargets: ["/", "/pricing", "/product"]
  },
  "/verify": {
    path: "/verify",
    pageType: "faq",
    indexable: true,
    primaryKeyword: "CBAM certificate verification",
    secondaryKeywords: ["signature verification"],
    domainNoun: "Verification lookup",
    pain: "Exporters needing to prove data quality and document hash validity to custom officials",
    outcome: "Verify CBAM Registry status and accredited verifier ready cryptographic seals",
    audience: "Verifier and customs",
    title: "CBAM Certificate Verification & Integrity Check | CBAMValid",
    description: "Verify your CBAM certificate verification code. Check the cryptographic signature, active state, and audit trail of your sealed compliance dossier.",
    h1: "Verify CBAM Certificate Verification Status",
    canonicalPath: "/verify",
    lastModifiedSource: "registry",
    authorityReferences: [],
    schemaTypes: ["BreadcrumbList"],
    internalLinkTargets: ["/", "/contact"]
  }
};
