import Link from "next/link";
import { CANONICAL_PRICING } from "@/lib/billing/pricing-config";

const SOFTWARE_FEATURES = [
  {
    title: "Customer-controlled data workspace",
    text: "Business users enter and maintain their own installation, production, emissions and evidence data.",
  },
  {
    title: "Automated calculation engine",
    text: "The application runs deterministic calculations and repeatable validation rules from the submitted data.",
  },
  {
    title: "Automated quality controls",
    text: "Missing fields, reconciliation differences and unsupported material inputs are surfaced before digital delivery.",
  },
  {
    title: "Automated digital delivery",
    text: "A successful lock generates downloadable PDF, JSON and XLSX files without manual preparation by CBAMValid personnel.",
  },
] as const;

const EXCLUDED_SERVICES = [
  "Government services, authority representation or access to government officials",
  "Registry filing, customs filing, permit applications or submissions on a customer’s behalf",
  "Consulting, advisory, managed compliance or manual dossier preparation",
  "Legal, tax or customs advice",
  "Accredited verification, certification, approval or assurance opinions",
  "Human review or approval of customer emissions data",
] as const;

export default function SoftwareProductHome() {
  return (
    <main id="main">
      <section className="hero">
        <div className="wrap hero-grid">
          <div>
            <span className="eyebrow">B2B SaaS · Automated digital delivery</span>
            <h1>
              Emissions Data Workspace
              <br />
              <span className="serif-i">and Document Generator</span>
            </h1>
            <p className="lede">
              CBAMValid is self-service business software. Customers enter and control their own data;
              the application automatically calculates, checks, stores and exports structured digital
              files for customer and supply-chain workflows.
            </p>
            <p className="aeo-lead">
              <strong>Product classification:</strong>{" "}
              <span className="speakable-answer">
                software access and automated digital delivery only. CBAMValid is not a government
                service and does not file, submit, certify, verify or communicate with any authority on
                behalf of customers.
              </span>
            </p>
            <p className="price-line">
              {CANONICAL_PRICING.priceFormatted} one-time per working file at lock.{" "}
              <span>No subscription. Drafting is free.</span>
            </p>
            <div className="hero-ctas">
              <Link className="btn btn-primary btn-lg" href="/register?next=/cases/new" prefetch={false}>
                Start Free Draft <span className="arr">→</span>
              </Link>
              <Link className="btn btn-ghost btn-lg" href="/demo">
                View Software Demo
              </Link>
              <Link className="btn btn-navy btn-lg" href="/pricing">
                See Software Pricing
              </Link>
            </div>
            <ul className="hero-micro">
              <li>Customer-entered data</li>
              <li>Automated calculations</li>
              <li>PDF · JSON · XLSX delivery</li>
            </ul>
          </div>

          <div className="price-card featured" style={{ alignSelf: "center" }}>
            <span className="badge-pop">Software product summary</span>
            <h3>What the customer buys</h3>
            <p className="sub">
              A one-time software unlock for one working file covering one operator, one installation
              and one reporting year.
            </p>
            <ul className="feat-list">
              <li>Unlimited customer-controlled drafts before lock</li>
              <li>Automated calculations and validation rules</li>
              <li>Customer-controlled evidence linking</li>
              <li>Automated PDF, JSON and XLSX generation</li>
              <li>Same-file correction re-locks included</li>
            </ul>
            <Link className="btn btn-primary" href="/product-classification">
              Review Product Classification <span className="arr">→</span>
            </Link>
          </div>
        </div>
      </section>

      <section className="section" style={{ background: "var(--paper-2)" }}>
        <div className="wrap">
          <div className="section-head center">
            <span className="eyebrow">Software operation</span>
            <h2>Four automated functions, one digital product</h2>
            <p>
              The paid deliverable is generated by the application from customer-controlled inputs. No
              professional service is bundled into the purchase.
            </p>
          </div>
          <div className="deliv-grid">
            {SOFTWARE_FEATURES.map((feature) => (
              <div className="deliv-card" key={feature.title}>
                <h3>{feature.title}</h3>
                <p>{feature.text}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="section">
        <div className="wrap">
          <div className="section-head">
            <span className="eyebrow">Commercial boundary</span>
            <h2>Services not sold by CBAMValid</h2>
            <p>
              Regulatory references inside the software are calculation inputs and documentation
              sources. They do not turn the product into a government, filing, consulting or
              certification service.
            </p>
          </div>
          <div className="price-card">
            <ul className="feat-list">
              {EXCLUDED_SERVICES.map((item) => (
                <li key={item}>{item}</li>
              ))}
            </ul>
          </div>
          <div className="hero-ctas" style={{ marginTop: "28px" }}>
            <Link className="btn btn-navy" href="/product">
              Product Capabilities
            </Link>
            <Link className="btn btn-ghost" href="/terms">
              Terms and Exclusions
            </Link>
            <Link className="btn btn-ghost" href="/refund-policy">
              Refund Policy
            </Link>
          </div>
        </div>
      </section>
    </main>
  );
}
