#!/usr/bin/env npx tsx
/**
 * FAZ P0 (J) — sandbox bootstrap.
 *
 * Provisions the hosted QA sandbox project and local config so that:
 *   - `cbam-desk-sandbox` exists (created when the caller has authority and
 *     quota; otherwise the script stops with EXTERNAL_BLOCKER)
 *   - required Google APIs are enabled
 *   - `.firebaserc` gains a `sandbox` alias
 *   - `.env.sandbox` is written with the sandbox-only runtime configuration
 *     (APP_ENV=sandbox, PADDLE_DISABLED=true, SYNTHETIC_DOSSIERS_ONLY=true)
 *
 * The production project `cbam-desk` is NEVER modified by this script.
 *
 * Usage:
 *   npm run sandbox:bootstrap
 */
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const SANDBOX_PROJECT = "cbam-desk-sandbox";
const PRODUCTION_PROJECT = "cbam-desk";
const REQUIRED_APIS = [
  "firestore.googleapis.com",
  "storage-api.googleapis.com",
  "cloudfunctions.googleapis.com",
  "run.googleapis.com",
  "secretmanager.googleapis.com",
  "cloudkms.googleapis.com",
  "identitytoolkit.googleapis.com",
];

const rootDir = process.cwd();

function run(command: string, args: string[], opts: { failOk?: boolean; capture?: boolean } = {}): {
  status: number;
  stdout: string;
  stderr: string;
} {
  const result = spawnSync(command, args, {
    encoding: "utf8",
    cwd: rootDir,
    timeout: 120_000,
    env: process.env,
  });
  const stdout = (result.stdout || "").trim();
  const stderr = (result.stderr || "").trim();
  if (!opts.failOk && result.status !== 0) {
    throw new Error(`${command} ${args.join(" ")} failed:\n${stdout}\n${stderr}`);
  }
  return { status: result.status ?? -1, stdout, stderr };
}

function projectExists(): boolean {
  const result = run("gcloud", ["projects", "describe", SANDBOX_PROJECT], { failOk: true });
  return result.status === 0 && result.stdout.includes(SANDBOX_PROJECT);
}

function ensureFirebasercAlias(): void {
  const firebasercPath = path.join(rootDir, ".firebaserc");
  let firebaserc: { projects: Record<string, string> };
  try {
    firebaserc = JSON.parse(fs.readFileSync(firebasercPath, "utf8"));
  } catch {
    firebaserc = { projects: {} };
  }
  firebaserc.projects ??= {};
  firebaserc.projects.sandbox = SANDBOX_PROJECT;
  if (!firebaserc.projects.default) firebaserc.projects.default = PRODUCTION_PROJECT;
  fs.writeFileSync(firebasercPath, `${JSON.stringify(firebaserc, null, 2)}\n`, "utf8");
  console.log(`PASS  .firebaserc sandbox alias -> ${SANDBOX_PROJECT}`);
}

function writeSandboxEnv(): void {
  const envPath = path.join(rootDir, ".env.sandbox");
  const content = [
    "# CBAMValid hosted QA sandbox configuration — generated by sandbox:bootstrap.",
    "# This file is for the isolated sandbox project only; it must never be deployed to cbam-desk.",
    "APP_ENV=sandbox",
    "PADDLE_DISABLED=true",
    "SYNTHETIC_DOSSIERS_ONLY=true",
    `NEXT_PUBLIC_FIREBASE_PROJECT_ID=${SANDBOX_PROJECT}`,
    "",
    "# Sandbox seed target (synthetic dossiers). NEVER set this to cbam-desk.",
    `FIREBASE_PROJECT=${SANDBOX_PROJECT}`,
    "",
  ].join("\n");
  fs.writeFileSync(envPath, content, "utf8");
  console.log(`PASS  .env.sandbox written (APP_ENV=sandbox, PADDLE_DISABLED=true, SYNTHETIC_DOSSIERS_ONLY=true)`);
}

function main(): void {
  console.log(`CBAMValid sandbox bootstrap — sandbox "${SANDBOX_PROJECT}"`);

  const exists = projectExists();
  if (exists) {
    console.log(`PASS  project ${SANDBOX_PROJECT} already exists`);
  } else {
    console.log(`INFO  project ${SANDBOX_PROJECT} does not exist — attempting creation`);
    const create = run("gcloud", ["projects", "create", SANDBOX_PROJECT, "--name=CBAMValid Sandbox"], { failOk: true });
    if (create.status !== 0) {
      const detail = `${create.stdout} ${create.stderr}`.trim().split("\n").slice(0, 3).join(" | ");
      console.error(`FAIL  project creation blocked — ${detail}`);
      // Local config is still prepared so the doctor can confirm isolation
      // and the sandbox alias; the hosted project itself remains blocked.
      ensureFirebasercAlias();
      writeSandboxEnv();
      console.error("      This is an EXTERNAL_BLOCKER: the sandbox project must be provisioned");
      console.error("      by an account with project-creation quota before hosted E2E can run.");
      console.error("      Local emulator E2E remains available.");
      console.error("BOOTSTRAP_STATUS=EXTERNAL_BLOCKER");
      process.exit(2);
    }
    console.log(`PASS  project ${SANDBOX_PROJECT} created (${create.stdout.trim()})`);
  }

  for (const api of REQUIRED_APIS) {
    const enable = run("gcloud", ["services", "enable", api, "--project", SANDBOX_PROJECT], { failOk: true });
    if (enable.status !== 0) {
      console.warn(`WARN  could not enable ${api} (${enable.stderr.split("\n")[0]})`);
    } else {
      console.log(`PASS  enabled ${api}`);
    }
  }

  ensureFirebasercAlias();
  writeSandboxEnv();

  console.log("BOOTSTRAP_STATUS=COMPLETE");
  process.exit(0);
}

void main();
