#!/usr/bin/env npx tsx
/**
 * FAZ P0 (J) — sandbox bootstrap.
 *
 * Provisions the hosted QA sandbox project and local config so that:
 *   - `cbam-desk-sandbox` exists as an actual Firebase project
 *   - required Google APIs are enabled
 *   - `.firebaserc` gains a `sandbox` alias
 *   - `.env.sandbox` is written with isolated Firebase and Paddle sandbox
 *     environment flags, without creating or storing credentials
 *
 * The production project `cbam-desk` is NEVER modified by this script.
 *
 * Usage:
 *   npm run sandbox:bootstrap
 */
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const SANDBOX_PROJECT = "cbam-desk-sandbox";
const PRODUCTION_PROJECT = "cbam-desk";
const REQUIRED_APIS = [
  "firebase.googleapis.com",
  "firebasehosting.googleapis.com",
  "firestore.googleapis.com",
  "storage-api.googleapis.com",
  "cloudfunctions.googleapis.com",
  "run.googleapis.com",
  "secretmanager.googleapis.com",
  "cloudkms.googleapis.com",
  "identitytoolkit.googleapis.com",
];

const rootDir = process.cwd();

function run(command: string, args: string[], opts: { failOk?: boolean; capture?: boolean } = {}): {
  status: number;
  stdout: string;
  stderr: string;
} {
  const result = spawnSync(command, args, {
    encoding: "utf8",
    cwd: rootDir,
    timeout: 120_000,
    env: process.env,
  });
  const stdout = (result.stdout || "").trim();
  const stderr = (result.stderr || "").trim();
  if (!opts.failOk && result.status !== 0) {
    throw new Error(`${command} ${args.join(" ")} failed:\n${stdout}\n${stderr}`);
  }
  return { status: result.status ?? -1, stdout, stderr };
}

function googleCloudProjectExists(): boolean {
  const result = run("gcloud", ["projects", "describe", SANDBOX_PROJECT], { failOk: true });
  return result.status === 0 && result.stdout.includes(SANDBOX_PROJECT);
}

function firebaseProjectExists(): boolean {
  const result = run("firebase", ["projects:list", "--json"], { failOk: true });
  return result.status === 0 && result.stdout.includes(`"${SANDBOX_PROJECT}"`);
}

function failExternalBlocker(detail: string): never {
  console.error(`FAIL  sandbox project provisioning blocked — ${detail}`);
  ensureFirebasercAlias();
  writeSandboxEnv();
  console.error("      This is an EXTERNAL_BLOCKER: create/enable cbam-desk-sandbox");
  console.error("      using the owner account, accept Firebase terms if prompted, and attach billing");
  console.error("      before hosted Functions/Hosting E2E can run.");
  console.error("      Local emulator and offline dossier E2E remain available.");
  console.error("BOOTSTRAP_STATUS=EXTERNAL_BLOCKER");
  process.exit(2);
}

function ensureFirebaseProject(): void {
  const gcpExists = googleCloudProjectExists();
  const firebaseExists = firebaseProjectExists();

  if (firebaseExists) {
    console.log(`PASS  Firebase project ${SANDBOX_PROJECT} already exists`);
    return;
  }

  if (!gcpExists) {
    console.log(`INFO  project ${SANDBOX_PROJECT} does not exist — creating Firebase project`);
    const create = run(
      "firebase",
      [
        "projects:create",
        SANDBOX_PROJECT,
        "--display-name",
        "CBAMValid Sandbox",
        "--json",
      ],
      { failOk: true }
    );
    if (create.status !== 0) {
      const detail = `${create.stdout} ${create.stderr}`.trim().split("\n").slice(0, 4).join(" | ");
      failExternalBlocker(detail);
    }
    console.log(`PASS  Firebase project ${SANDBOX_PROJECT} created`);
    return;
  }

  console.log(`INFO  Google Cloud project exists without Firebase — adding Firebase resources`);
  const addFirebase = run(
    "firebase",
    ["projects:addfirebase", SANDBOX_PROJECT, "--json"],
    { failOk: true }
  );
  if (addFirebase.status !== 0) {
    const detail = `${addFirebase.stdout} ${addFirebase.stderr}`
      .trim()
      .split("\n")
      .slice(0, 4)
      .join(" | ");
    failExternalBlocker(detail);
  }
  console.log(`PASS  Firebase resources added to ${SANDBOX_PROJECT}`);
}

function ensureFirebasercAlias(): void {
  const firebasercPath = path.join(rootDir, ".firebaserc");
  let firebaserc: { projects: Record<string, string> };
  try {
    firebaserc = JSON.parse(fs.readFileSync(firebasercPath, "utf8"));
  } catch {
    firebaserc = { projects: {} };
  }
  firebaserc.projects ??= {};
  firebaserc.projects.sandbox = SANDBOX_PROJECT;
  if (!firebaserc.projects.default) firebaserc.projects.default = PRODUCTION_PROJECT;
  fs.writeFileSync(firebasercPath, `${JSON.stringify(firebaserc, null, 2)}\n`, "utf8");
  console.log(`PASS  .firebaserc sandbox alias -> ${SANDBOX_PROJECT}`);
}

function writeSandboxEnv(): void {
  const envPath = path.join(rootDir, ".env.sandbox");
  const content = [
    "# CBAMValid hosted QA sandbox configuration — generated by sandbox:bootstrap.",
    "# This file is for the isolated sandbox project only; it must never be deployed to cbam-desk.",
    "APP_ENV=sandbox",
    "SYNTHETIC_DOSSIERS_ONLY=true",
    `NEXT_PUBLIC_FIREBASE_PROJECT_ID=${SANDBOX_PROJECT}`,
    `FIREBASE_PROJECT=${SANDBOX_PROJECT}`,
    "FUNCTIONS_REGION=europe-west1",
    "",
    "# Paddle sandbox mode. Add real sandbox credentials locally or through the sandbox runtime/Secret Manager.",
    "# Never place live Paddle credentials in cbam-desk-sandbox.",
    "PADDLE_ENV=sandbox",
    "NEXT_PUBLIC_PADDLE_ENV=sandbox",
    "NEXT_PUBLIC_PADDLE_SANDBOX=true",
    "PADDLE_API_KEY=",
    "NEXT_PUBLIC_PADDLE_CLIENT_TOKEN=",
    "NEXT_PUBLIC_PADDLE_PRICE_ID=",
    "PADDLE_WEBHOOK_SECRET=",
    "",
  ].join("\n");
  fs.writeFileSync(envPath, content, { encoding: "utf8", mode: 0o600 });
  console.log(
    "PASS  .env.sandbox written (isolated Firebase project + Paddle sandbox flags; credentials remain blank)"
  );
}

function main(): void {
  console.log(`CBAMValid sandbox bootstrap — sandbox "${SANDBOX_PROJECT}"`);

  ensureFirebaseProject();

  for (const api of REQUIRED_APIS) {
    const enable = run("gcloud", ["services", "enable", api, "--project", SANDBOX_PROJECT], { failOk: true });
    if (enable.status !== 0) {
      console.warn(`WARN  could not enable ${api} (${enable.stderr.split("\n")[0]})`);
    } else {
      console.log(`PASS  enabled ${api}`);
    }
  }

  ensureFirebasercAlias();
  writeSandboxEnv();

  console.log("BOOTSTRAP_STATUS=COMPLETE");
  process.exit(0);
}

void main();
