/**
 * FAZ P0 — Field-based guidance registry.
 *
 * Every material field carries a full guidance record telling the operator
 * why the field is required, what format to use, which documents are accepted,
 * who should issue them, the period they must cover and how a gap affects the
 * report. Guidance records are also the source for the wizard link options and
 * the step validation registry (see wizard-validation.ts).
 */

export type BlockingLevel = "MATERIAL_REQUIRED" | "REQUIRED" | "CONDITIONAL" | "OPTIONAL";

export interface FieldGuidanceRecord {
  fieldPath: string;
  label: string;
  required: boolean;
  whyRequired: string;
  expectedFormat: string;
  acceptedEvidenceTypes: readonly string[];
  preferredIssuerCategories: readonly string[];
  example: string;
  responsibleParty: "OPERATOR" | "EXTERNAL_VERIFIER" | "SYSTEM";
  relatedStep: number;
  legalBasis: string;
  blockingLevel: BlockingLevel;
  periodGuidance: string;
  gapImpact: string;
}

export const FIELD_GUIDANCE: readonly FieldGuidanceRecord[] = [
  {
    fieldPath: "importerIdentity.legalName",
    label: "Importer legal name",
    required: true,
    whyRequired: "The CBAM declarant (importer or indirect customs representative) must be identified on every official filing and on the verifier dossier cover.",
    expectedFormat: "Full legal name exactly as registered in the EU commercial register; never a trading name alone.",
    acceptedEvidenceTypes: ["COMMERCIAL_REGISTRY_EXTRACT", "EORI_REGISTRATION", "TAX_REGISTRATION"],
    preferredIssuerCategories: ["NATIONAL_REGISTRY", "GOVERNMENT_AUTHORITY"],
    example: "CBAMValid Importer B.V.",
    responsibleParty: "OPERATOR",
    relatedStep: 1,
    legalBasis: "Regulation (EU) 2023/956, Art. 9(1); Commission Implementing Regulation (EU) 2025/2547.",
    blockingLevel: "MATERIAL_REQUIRED",
    periodGuidance: "The record must be current at the reporting-period end date.",
    gapImpact: "A missing importer identity blocks the dossier: no declarant means no report can be addressed.",
  },
  {
    fieldPath: "importerIdentity.eoriNumber",
    label: "Declarant EORI number",
    required: true,
    whyRequired: "The EORI number is the stable identifier the EU customs authority uses for the declarant; it links every customs declaration and is required for the Registry submission.",
    expectedFormat: "Two-letter country prefix followed by 6–15 alphanumeric characters, no spaces (for example NL123456789AB).",
    acceptedEvidenceTypes: [
      "EORI_REGISTRATION_RECORD",
      "CUSTOMS_DECLARATION",
      "CUSTOMS_AUTHORITY_CONFIRMATION",
    ],
    preferredIssuerCategories: ["CUSTOMS_AUTHORITY", "GOVERNMENT_AUTHORITY"],
    example: "NL123456789AB",
    responsibleParty: "OPERATOR",
    relatedStep: 1,
    legalBasis: "Commission Implementing Regulation (EU) 2025/2547; Union Customs Code Art. 9.",
    blockingLevel: "MATERIAL_REQUIRED",
    periodGuidance: "The EORI must be the active declarant EORI for the reporting period.",
    gapImpact: "An empty or un-evidenced EORI blocks Step 1 and the seal: the declarant identity is a hard blocker.",
  },
  {
    fieldPath: "exporterIdentity.legalName",
    label: "Exporter/operator legal name",
    required: true,
    whyRequired: "The non-EU producer whose installation produces the declared goods must be identified so the verifier can match the operator dossier to the installation.",
    expectedFormat: "Full legal name exactly as it appears in the operator company register.",
    acceptedEvidenceTypes: ["COMMERCIAL_REGISTRY_EXTRACT", "TAX_REGISTRATION", "OPERATOR_DECLARATION"],
    preferredIssuerCategories: ["NATIONAL_REGISTRY", "GOVERNMENT_AUTHORITY", "OPERATOR_CONTROLLED"],
    example: "Verified Steel Operator A.S.",
    responsibleParty: "OPERATOR",
    relatedStep: 1,
    legalBasis: "Regulation (EU) 2023/956, Art. 9(1) and Annex IV.",
    blockingLevel: "MATERIAL_REQUIRED",
    periodGuidance: "Legal identity must be stable across the whole reporting period.",
    gapImpact: "Missing operator identity prevents the report from being tied to the producing installation.",
  },
  {
    fieldPath: "reportingPeriod.year",
    label: "Reporting year",
    required: true,
    whyRequired: "The dossier is scoped to a single reporting year; every production, emissions and evidence record must cover exactly this period.",
    expectedFormat: "Four-digit calendar year from 2026 onward, matching the period used across all source documents.",
    acceptedEvidenceTypes: [
      "SIGNED_PERIOD_CLOSURE_SHEET",
      "MONITORING_PERIOD_CONTROL_RECORD",
      "ANNUAL_LEDGER_CLOSURE",
    ],
    preferredIssuerCategories: ["OPERATOR_CONTROLLED", "INDEPENDENT_AUDITOR"],
    example: "2026",
    responsibleParty: "OPERATOR",
    relatedStep: 1,
    legalBasis: "Commission Implementing Regulation (EU) 2025/2547, reporting-period provisions.",
    blockingLevel: "MATERIAL_REQUIRED",
    periodGuidance: "The year defines the required coverage interval; evidence must cover 2026-01-01 to 2026-12-31.",
    gapImpact: "An invalid or unsupported year blocks the reporting-period assessment and therefore the seal.",
  },
  {
    fieldPath: "reportingPeriod.quarter",
    label: "Reporting period / quarter",
    required: true,
    whyRequired: "ANNUAL (definitive) or quarterly interim scope must be consistent between the dossier and the monitoring plan.",
    expectedFormat: "One of ANNUAL, Q1, Q2, Q3, Q4.",
    acceptedEvidenceTypes: ["MONITORING_PLAN", "PERIOD_CONTROL_RECORD"],
    preferredIssuerCategories: ["OPERATOR_CONTROLLED"],
    example: "ANNUAL",
    responsibleParty: "OPERATOR",
    relatedStep: 1,
    legalBasis: "Commission Implementing Regulation (EU) 2025/2547.",
    blockingLevel: "REQUIRED",
    periodGuidance: "Period label must match every linked evidence reportingPeriod value.",
    gapImpact: "A mismatched period label creates coverage gaps that block readiness.",
  },
  {
    fieldPath: "goods.*.cnCode",
    label: "CN code",
    required: true,
    whyRequired: "The Combined Nomenclature code determines the CBAM goods category, the applicable rules and the certificate-relevant treatment of the declared goods.",
    expectedFormat: "Exactly 8 digits, no spaces or punctuation (for example 72011011).",
    acceptedEvidenceTypes: [
      "CUSTOMS_DECLARATION",
      "BINDING_TARIFF_INFORMATION",
      "AUTHORISED_CLASSIFICATION_MEMORANDUM",
    ],
    preferredIssuerCategories: ["CUSTOMS_AUTHORITY", "GOVERNMENT_AUTHORITY"],
    example: "72011011",
    responsibleParty: "OPERATOR",
    relatedStep: 2,
    legalBasis: "Regulation (EU) 2023/956 Annex I; Combined Nomenclature 2026.",
    blockingLevel: "MATERIAL_REQUIRED",
    periodGuidance: "The classification must be valid for the reporting period.",
    gapImpact: "An empty CN code blocks Step 2 and sealing; an unsupported CN code blocks the seal with an invalid classification.",
  },
  {
    fieldPath: "goods.*.sector",
    label: "CBAM sector",
    required: true,
    whyRequired: "The sector selects the default calculation rules and the sector-specific methodology that must be evidenced.",
    expectedFormat: "One of the supported CBAM sectors matching the CN code and the production route.",
    acceptedEvidenceTypes: ["CUSTOMS_DECLARATION", "CN_CLASSIFICATION_REASONING"],
    preferredIssuerCategories: ["CUSTOMS_AUTHORITY", "OPERATOR_CONTROLLED"],
    example: "IRON_AND_STEEL",
    responsibleParty: "OPERATOR",
    relatedStep: 2,
    legalBasis: "Regulation (EU) 2023/956 Annex I.",
    blockingLevel: "REQUIRED",
    periodGuidance: "Sector must be stable across the period.",
    gapImpact: "A wrong sector applies the wrong ruleset and produces an incorrect certificate-relevant result.",
  },
  {
    fieldPath: "goods.*.productionVolume",
    label: "Production quantity",
    required: true,
    whyRequired: "Production quantity is the denominator of the specific embedded emissions; without it no intensity can be calculated and no goods-level result is verifiable.",
    expectedFormat: "Positive net quantity in tonnes (or kilograms); exclude out-of-period production.",
    acceptedEvidenceTypes: [
      "SIGNED_PRODUCTION_LEDGER",
      "ERP_PERIOD_EXPORT",
      "MASS_BALANCE_RECONCILIATION",
      "INDEPENDENT_PRODUCTION_RECONCILIATION",
    ],
    preferredIssuerCategories: ["OPERATOR_CONTROLLED", "INDEPENDENT_AUDITOR"],
    example: "120.5",
    responsibleParty: "OPERATOR",
    relatedStep: 2,
    legalBasis: "Commission Implementing Regulation (EU) 2025/2547, activity data requirements.",
    blockingLevel: "MATERIAL_REQUIRED",
    periodGuidance: "The quantity must be reconciled to the reporting-period ledger, inventory and dispatch.",
    gapImpact: "Missing production quantity blocks the goods row and the seal; the report cannot compute an intensity.",
  },
  {
    fieldPath: "goods.*.allocationShare",
    label: "Allocation share (0–1)",
    required: true,
    whyRequired: "When more than one good shares installation emissions, each good needs a documented allocation share and all shares must reconcile to exactly 1.",
    expectedFormat: "Decimal fraction greater than 0 and at most 1; all goods must sum to 1 within tolerance.",
    acceptedEvidenceTypes: ["ALLOCATION_WORKBOOK", "PRODUCTION_LEDGER", "ACCEPTED_METHODOLOGY_DECISION"],
    preferredIssuerCategories: ["OPERATOR_CONTROLLED", "INDEPENDENT_AUDITOR"],
    example: "0.6",
    responsibleParty: "OPERATOR",
    relatedStep: 2,
    legalBasis: "Commission Implementing Regulation (EU) 2025/2547, allocation provisions.",
    blockingLevel: "CONDITIONAL",
    periodGuidance: "The allocation method must be evidenced for the reporting period.",
    gapImpact: "Unreconciled allocation shares block the seal with an allocation-reconciliation finding.",
  },
  {
    fieldPath: "goods.*.shipmentRecords",
    label: "Shipment / product description",
    required: true,
    whyRequired: "The shipment description ties the goods row to invoices, packing lists and dispatch records used by the verifier.",
    expectedFormat: "Short product and shipment population description consistent with the CN code.",
    acceptedEvidenceTypes: ["COMMERCIAL_INVOICE", "PACKING_LIST", "BILL_OF_LADING"],
    preferredIssuerCategories: ["OPERATOR_CONTROLLED", "SUPPLIER"],
    example: "Non-alloy pig iron ingots, 2026 annual production",
    responsibleParty: "OPERATOR",
    relatedStep: 2,
    legalBasis: "Regulation (EU) 2023/956, Art. 9(2).",
    blockingLevel: "REQUIRED",
    periodGuidance: "Description must reflect the reporting-period shipment population.",
    gapImpact: "An empty description weakens the verifier's ability to match the row to trade documents.",
  },
  {
    fieldPath: "installation.name",
    label: "Installation name",
    required: true,
    whyRequired: "The physical production installation is the unit of CBAM reporting; the name ties every emission and evidence record to the correct boundary.",
    expectedFormat: "Legal or operational installation name as used in permits and monitoring records.",
    acceptedEvidenceTypes: ["OPERATING_PERMIT", "ENVIRONMENTAL_PERMIT", "MONITORING_PLAN"],
    preferredIssuerCategories: ["GOVERNMENT_AUTHORITY", "OPERATOR_CONTROLLED"],
    example: "Verified Integrated Steel Installation",
    responsibleParty: "OPERATOR",
    relatedStep: 3,
    legalBasis: "Regulation (EU) 2023/956, Art. 9(2).",
    blockingLevel: "MATERIAL_REQUIRED",
    periodGuidance: "Installation identity must not change mid-period.",
    gapImpact: "Missing installation identity is a hard seal blocker.",
  },
  {
    fieldPath: "installation.country",
    label: "Installation country",
    required: true,
    whyRequired: "Country of origin determines default emission factors, the applicable carbon-price treatment and the non-EU production basis.",
    expectedFormat: "ISO country code or country name used consistently across the dossier (for example TR).",
    acceptedEvidenceTypes: ["OPERATING_PERMIT", "REGISTERED_ADDRESS", "INSTALLATION_DECLARATION"],
    preferredIssuerCategories: ["GOVERNMENT_AUTHORITY", "NATIONAL_REGISTRY"],
    example: "TR",
    responsibleParty: "OPERATOR",
    relatedStep: 3,
    legalBasis: "Regulation (EU) 2023/956, Annex IV.",
    blockingLevel: "MATERIAL_REQUIRED",
    periodGuidance: "Country must be the physical production location, not the invoicing country.",
    gapImpact: "Wrong country applies the wrong factors and carbon-price treatment.",
  },
  {
    fieldPath: "installation.productionRoute",
    label: "Production route",
    required: true,
    whyRequired: "The production route (technology) selects which source streams, process emissions and default values apply to the goods.",
    expectedFormat: "State the actual route and relevant furnace/process type (for example Blast Furnace Route (BF-BOF)).",
    acceptedEvidenceTypes: ["PROCESS_FLOW_DIAGRAM", "MONITORING_PLAN", "PRODUCTION_ROUTE_DESCRIPTION"],
    preferredIssuerCategories: ["OPERATOR_CONTROLLED"],
    example: "Blast Furnace Route (BF-BOF)",
    responsibleParty: "OPERATOR",
    relatedStep: 3,
    legalBasis: "Commission Implementing Regulation (EU) 2025/2547, monitoring-plan requirements.",
    blockingLevel: "REQUIRED",
    periodGuidance: "Route must cover the whole reporting period.",
    gapImpact: "A missing route leaves the process and source-stream registers without a basis.",
  },
  {
    fieldPath: "installation.systemBoundaries",
    label: "System-boundary statement",
    required: true,
    whyRequired: "The system boundary defines which processes, source streams and energy flows are inside the installation and therefore included in the emissions reported.",
    expectedFormat: "Explicit statement of included and excluded processes, source streams and energy flows; unexplained exclusions must not be omitted.",
    acceptedEvidenceTypes: [
      "MONITORING_PLAN",
      "INSTALLATION_PERMIT_SCOPE",
      "PROCESS_MAP",
      "CONTROLLED_SYSTEM_BOUNDARY_STATEMENT",
    ],
    preferredIssuerCategories: ["OPERATOR_CONTROLLED", "GOVERNMENT_AUTHORITY"],
    example: "Coke preparation, sinter plant, blast furnace, basic oxygen furnace, casting and finishing operations within the controlled installation boundary.",
    responsibleParty: "OPERATOR",
    relatedStep: 3,
    legalBasis: "Regulation (EU) 2023/956, Annex IV; Commission Implementing Regulation (EU) 2025/2547.",
    blockingLevel: "MATERIAL_REQUIRED",
    periodGuidance: "The boundary must be stable for the reporting period.",
    gapImpact: "Missing system-boundary support blocks the seal unless an accepted methodology decision records the boundary (REQ-INST-BOUNDS).",
  },
  {
    fieldPath: "installation.monitoringPlanId",
    label: "Monitoring plan",
    required: true,
    whyRequired: "The monitoring plan documents how activity data and emissions are measured and controlled inside the boundary.",
    expectedFormat: "Plan identifier and version as issued by the operator.",
    acceptedEvidenceTypes: ["MONITORING_PLAN", "MONITORING_PLAN_UPDATE_RECORD"],
    preferredIssuerCategories: ["OPERATOR_CONTROLLED", "INDEPENDENT_AUDITOR"],
    example: "MP-SP-2026-v2",
    responsibleParty: "OPERATOR",
    relatedStep: 3,
    legalBasis: "Commission Implementing Regulation (EU) 2025/2546, Art. 6.",
    blockingLevel: "REQUIRED",
    periodGuidance: "The plan version applied to the reporting period.",
    gapImpact: "A missing monitoring plan leaves the monitoring-plan component and boundary evidence unsupported.",
  },
  {
    fieldPath: "directEmissions",
    label: "Total direct emissions",
    required: true,
    whyRequired: "Direct installation emissions (combustion and process) inside the boundary are the primary certificate-relevant figure for Annex II goods.",
    expectedFormat: "Total tCO2e for the reporting period; do not enter an intensity value.",
    acceptedEvidenceTypes: [
      "FUEL_ACTIVITY_LEDGER",
      "LABORATORY_ANALYSIS",
      "METER_RECORD",
      "DIRECT_EMISSIONS_CALCULATION_WORKBOOK",
    ],
    preferredIssuerCategories: ["OPERATOR_CONTROLLED", "INDEPENDENT_AUDITOR", "ACCREDITED_LAB"],
    example: "15240",
    responsibleParty: "OPERATOR",
    relatedStep: 4,
    legalBasis: "Commission Implementing Regulation (EU) 2025/2547; Regulation (EU) 2023/956 Annex IV.",
    blockingLevel: "MATERIAL_REQUIRED",
    periodGuidance: "Must cover the full reporting period with no unmeasured intervals.",
    gapImpact: "Missing direct emissions blocks the seal; the calculation annex cannot reconcile the goods totals.",
  },
  {
    fieldPath: "electricityConsumed",
    label: "Electricity consumed",
    required: true,
    whyRequired: "Electricity consumption drives the indirect emissions component; it must be metered inside the boundary for the reporting period.",
    expectedFormat: "MWh. Convert kWh to MWh by dividing by 1,000.",
    acceptedEvidenceTypes: ["ELECTRICITY_METER", "SUPPLIER_INVOICE", "ALLOCATION_RECONCILIATION"],
    preferredIssuerCategories: ["OPERATOR_CONTROLLED", "REGULATED_UTILITY", "GRID_OPERATOR"],
    example: "42000",
    responsibleParty: "OPERATOR",
    relatedStep: 5,
    legalBasis: "Regulation (EU) 2023/956, Annex IV, indirect emissions provisions.",
    blockingLevel: "MATERIAL_REQUIRED",
    periodGuidance: "Metered consumption must reconcile to supplier invoices for the reporting period.",
    gapImpact: "Missing or unmetered electricity blocks the indirect-emissions result.",
  },
  {
    fieldPath: "gridEmissionFactor",
    label: "Grid emission factor",
    required: true,
    whyRequired: "The grid factor converts electricity consumption into indirect emissions; the correct factor depends on the grid, geography and reporting period.",
    expectedFormat: "tCO2e/MWh (for example 0.4344). Decimal comma is normalized to a dot; divide kgCO2e/MWh or gCO2e/kWh by 1,000.",
    acceptedEvidenceTypes: [
      "OFFICIAL_GRID_OPERATOR_PUBLICATION",
      "COMPETENT_AUTHORITY_FACTOR",
      "SUPPLIER_SPECIFIC_VERIFIED_FACTOR",
    ],
    preferredIssuerCategories: ["GRID_OPERATOR", "GOVERNMENT_AUTHORITY", "REGULATED_UTILITY"],
    example: "0.4344",
    responsibleParty: "OPERATOR",
    relatedStep: 5,
    legalBasis: "Commission Implementing Regulation (EU) 2025/2547, electricity-factor provisions.",
    blockingLevel: "MATERIAL_REQUIRED",
    periodGuidance: "The factor must be valid for the reporting year and electricity source.",
    gapImpact: "An unsupported or mis-scaled factor silently distorts the indirect-emissions total.",
  },
  {
    fieldPath: "precursors.*",
    label: "Precursor inputs",
    required: false,
    whyRequired: "Embedded emissions of precursors must be added to the goods total when precursors are consumed; a documented no-precursor decision is required otherwise.",
    expectedFormat: "Per precursor: name, country of origin, consumed quantity (t), direct and indirect embedded emissions (tCO2e).",
    acceptedEvidenceTypes: ["BILL_OF_MATERIALS", "MASS_BALANCE", "SUPPLIER_EMISSIONS_COMMUNICATION"],
    preferredIssuerCategories: ["OPERATOR_CONTROLLED", "SUPPLIER"],
    example: "Hot briquetted iron (HBI), 800 t, 320 tCO2e direct, 40 tCO2e indirect",
    responsibleParty: "OPERATOR",
    relatedStep: 6,
    legalBasis: "Regulation (EU) 2023/956, Annex IV precursor rules.",
    blockingLevel: "CONDITIONAL",
    periodGuidance: "Precursor quantities must be consumed inside the reporting period.",
    gapImpact: "Missing precursor treatment leaves embedded emissions understated or blocks the seal on a precursor finding.",
  },
  {
    fieldPath: "carbonPriceRecords.*.amountPaid",
    label: "Carbon price amount paid",
    required: false,
    whyRequired: "A carbon price paid in the country of origin can reduce the CBAM price exposure when the payment is proven and reconciled to applicable emissions.",
    expectedFormat: "Positive monetary amount in the declared currency (EUR, USD, GBP or TRY).",
    acceptedEvidenceTypes: ["OFFICIAL_ASSESSMENT", "PAYMENT_RECEIPT", "CARBON_PRICE_RECORD"],
    preferredIssuerCategories: ["GOVERNMENT_AUTHORITY", "REGULATED_UTILITY", "INDEPENDENT_AUDITOR"],
    example: "12500000",
    responsibleParty: "OPERATOR",
    relatedStep: 7,
    legalBasis: "Regulation (EU) 2023/956, Art. 9; Commission Implementing Regulation (EU) 2025/2548.",
    blockingLevel: "CONDITIONAL",
    periodGuidance: "Payments must relate to emissions arising in the reporting period.",
    gapImpact: "An unproven carbon price is disallowed and creates a material finding.",
  },
  {
    fieldPath: "carbonPriceRecords.*.applicableEmissions",
    label: "Carbon price applicable emissions",
    required: false,
    whyRequired: "The deduction is limited to the emissions on which the carbon price was actually paid; this must reconcile to the period emissions.",
    expectedFormat: "Positive tCO2e not exceeding the installation emissions for the period.",
    acceptedEvidenceTypes: ["OFFICIAL_ASSESSMENT", "PAYMENT_RECEIPT", "CARBON_PRICE_RECORD"],
    preferredIssuerCategories: ["GOVERNMENT_AUTHORITY", "INDEPENDENT_AUDITOR"],
    example: "480000",
    responsibleParty: "OPERATOR",
    relatedStep: 7,
    legalBasis: "Regulation (EU) 2023/956, Art. 9.",
    blockingLevel: "CONDITIONAL",
    periodGuidance: "Must reconcile to the reporting-period emissions base.",
    gapImpact: "An overstated deduction is corrected to zero and flagged as a finding.",
  },
  {
    fieldPath: "carbonPriceRecords.*.proofOfPaymentEvidenceId",
    label: "Carbon price payment evidence",
    required: false,
    whyRequired: "Proof of payment links the recorded amount to the emissions assessment and the currency conversion used.",
    expectedFormat: "Link to an approved evidence record; the record must show the amount, period and payer.",
    acceptedEvidenceTypes: ["OFFICIAL_ASSESSMENT", "PAYMENT_RECEIPT"],
    preferredIssuerCategories: ["GOVERNMENT_AUTHORITY", "REGULATED_UTILITY"],
    example: "evidenceId of the payment receipt",
    responsibleParty: "OPERATOR",
    relatedStep: 7,
    legalBasis: "Regulation (EU) 2023/956, Art. 9.",
    blockingLevel: "CONDITIONAL",
    periodGuidance: "Payment evidence must cover the reporting period.",
    gapImpact: "Unlinked payment evidence disallows the deduction.",
  },
] as const;

export type FieldGuidancePath = (typeof FIELD_GUIDANCE)[number]["fieldPath"];

export function getFieldGuidance(fieldPath: string): FieldGuidanceRecord | undefined {
  return FIELD_GUIDANCE.find((record) => record.fieldPath === fieldPath);
}

/**
 * Resolve a guidance record for a concrete instance path such as "goods.0.cnCode"
 * by stripping the array index (goods.0.cnCode → goods.*.cnCode).
 */
export function getFieldGuidanceForPath(instancePath: string): FieldGuidanceRecord | undefined {
  const normalized = instancePath
    .split(".")
    .map((segment) => (/^\d+$/.test(segment) ? "*" : segment))
    .join(".");
  return getFieldGuidance(normalized);
}

export const FIELD_GUIDANCE_BY_PATH: ReadonlyMap<string, FieldGuidanceRecord> = new Map(
  FIELD_GUIDANCE.map((record) => [record.fieldPath, record])
);
